# Setup
title:               IEEE 802.15.4 & 6LoWPAN in Linux
tagline:             'Linux-Wpan'
description:         ''
url:                 http://linux-wpan.org
baseurl:             ''
paginate:            9

# About/contact
author:
  name:              Stefan Schmidt
  url:               ''
  email:             stefan@datenfreihafen.org
